name: Build macOS DMG

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15'

    - name: Install dependencies
      run: npm install

    - name: Build DMG
      run: npm run dist

    - name: Upload DMG Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DMG
        path: dist/*.dmg

    # Display status message after successful build
    - name: Display Success Message
      run: echo "DMG built successfully!"

    # Add additional steps as per your requirements
